/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odevv;
import static spark.Spark.port;

import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String change_port = System.getenv("PORT");

        int port = change_port != null ? Integer.parseInt(System.getenv("PORT")) : 4567;
        port(port);
    }
    public static boolean sliderCountCal(ArrayList<String> sliderItems,String[]images,int baslangic,int son,int sliderItemCount){
        ArrayList<ArrayList<String>> slider = new ArrayList<>();
        double sliderCount = Math.ceil(sliderItems.size()/sliderItemCount);
        double artis;
        if(sliderItems.size()< son ) son = sliderItems.size();
        for(int i = 0; i < sliderCount;i++){
            for(int j = baslangic; j < son; j++){
                sliderItems.add(images[j]);
            }
            slider.add(sliderItems);
            sliderItems.clear();
            if(images.length % sliderItemCount == 0){
                artis = sliderItemCount;
            } 
            else{
                artis = Math.ceil(images.length % sliderItemCount);
                if(son == images.length - artis && sliderItemCount != 1){
                    artis = images.length % sliderItemCount;
                }
                else{
                    artis = sliderItemCount;
                }
            }
            son += artis;
        }
        if(slider.size() == 0) return false;     
        else if(images.length == 0) return false;         
        else if(son == 0) return false;
        else if(sliderCount == 0) return false;
        else if(slider.size()/sliderItemCount == sliderCount) return true;
        return true;
    }
}
